version = 1

test_patterns = [
  'pycoal/tests/**'
]

exclude_patterns = [
  'docs/**',
  'examples/**'
]

[[analyzers]]
name = 'python'
enabled = true
runtime_version = '3.x.x'

name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "Dockerfile"
  ]

  trusted_registries = [
    "docker.io"
  ]
